/**
 * Paystack Service
 *
 * Handles all direct communication with the Paystack API.
 * PRINCIPLE: This service never processes business logic.
 *            It only talks to Paystack and returns raw results.
 *
 * IDEMPOTENCY PRINCIPLE:
 *   Every transaction reference is generated BY US (UUID), not by Paystack.
 *   This ensures we have full control over the idempotency key from the moment
 *   a payment attempt begins, before any network call is made.
 */

const axios = require('axios');
const crypto = require('crypto');

const PAYSTACK_BASE_URL = 'https://api.paystack.co';

class PaystackService {
    constructor() {
        this.secretKey = process.env.PAYSTACK_SECRET_KEY;

        if (!this.secretKey) {
            console.warn('[PaystackService] WARNING: PAYSTACK_SECRET_KEY is not set. Payment initialization will fail.');
        }
    }

    /**
     * Get Axios instance with auth headers
     */
    _getClient(secretKey) {
        const key = secretKey || this.secretKey;
        return axios.create({
            baseURL: PAYSTACK_BASE_URL,
            headers: {
                Authorization: `Bearer ${key}`,
                'Content-Type': 'application/json',
            },
            timeout: 10000, // 10 second timeout — never hang indefinitely
        });
    }

    /**
     * Initialize a Paystack transaction.
     *
     * @param {Object} params
     * @param {string} params.reference - OUR generated UUID (the idempotency key)
     * @param {string} params.email - Customer email
     * @param {number} params.amountKobo - Amount in KOBO (NGN * 100)
     * @param {string} params.callbackUrl - Where Paystack redirects after payment
     * @param {Object} params.metadata - { tenantId, orderId, cartId, userId }
     * @param {string} [params.secretKey] - Optional tenant-specific key (falls back to env)
     * @returns {Object} { authorization_url, access_code, reference }
     */
    async initializeTransaction({ reference, email, amountKobo, callbackUrl, metadata, secretKey }) {
        const client = this._getClient(secretKey);

        try {
            const response = await client.post('/transaction/initialize', {
                reference,       // OUR reference — Paystack will use this exact value
                email,
                amount: amountKobo,
                currency: 'NGN',
                callback_url: callbackUrl,
                metadata: {
                    ...metadata,
                    // Paystack will echo these back in the webhook event.data.metadata
                    cancel_action: callbackUrl,
                },
                channels: ['card', 'bank', 'ussd', 'bank_transfer'],
            });

            if (!response.data.status) {
                throw new Error(`Paystack init failed: ${response.data.message}`);
            }

            return response.data.data; // { authorization_url, access_code, reference }
        } catch (err) {
            const msg = err.response?.data?.message || err.message;
            console.error('[PaystackService] initializeTransaction failed:', msg);
            throw new Error(`Payment gateway error: ${msg}`);
        }
    }

    /**
     * Verify a transaction directly with Paystack.
     * Use ONLY for emergency reconciliation — NOT in the normal flow.
     * Normal flow relies 100% on the webhook.
     *
     * @param {string} reference - The transaction reference
     * @param {string} [secretKey] - Optional tenant key
     */
    async verifyTransaction(reference, secretKey) {
        const client = this._getClient(secretKey);

        try {
            const response = await client.get(`/transaction/verify/${encodeURIComponent(reference)}`);

            if (!response.data.status) {
                throw new Error(`Paystack verify failed: ${response.data.message}`);
            }

            return response.data.data;
        } catch (err) {
            const msg = err.response?.data?.message || err.message;
            console.error('[PaystackService] verifyTransaction failed:', msg);
            throw new Error(`Payment verification error: ${msg}`);
        }
    }

    /**
     * Verify a Paystack webhook signature.
     *
     * SECURITY: This MUST be called before processing any webhook payload.
     *           A forged webhook without the correct signature is silently rejected.
     *
     * @param {Buffer|string} rawBody - The raw request body (MUST be raw bytes, not parsed JSON)
     * @param {string} signature - The value of x-paystack-signature header
     * @param {string} [secretKey] - Optional tenant key (falls back to env)
     * @returns {boolean}
     */
    verifyWebhookSignature(rawBody, signature, secretKey) {
        const key = secretKey || this.secretKey;
        if (!key) return false;

        const hash = crypto
            .createHmac('sha512', key)
            .update(rawBody)
            .digest('hex');

        return hash === signature;
    }
}

// Singleton
module.exports = new PaystackService();
